apiVersion: v1
kind: Service
metadata:
  namespace: vote
  name: redis
spec:
  selector:
    app: redis-deployment
  ports:
    - name: http
      protocol: TCP
      port: 6379
      targetPort: 6379